# Generated by Django 3.0.8 on 2020-07-13 16:22

from django.db import migrations, models
import django.db.models.deletion
import smartqueue.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=63)),
                ('max_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_datetime', models.DateTimeField(max_length=15, null=True)),
                ('close_datetime', models.DateTimeField(max_length=15, null=True)),
                ('max_capacity', models.IntegerField()),
                ('address', models.CharField(max_length=63)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartqueue.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('occupant_sensor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'RESERVED'), (2, 'CANCELED'), (3, 'MISSED'), (4, 'COMPLETED')], default=smartqueue.models.ReservationState['RESERVED'])),
                ('reward_points', models.IntegerField()),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartqueue.Person')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartqueue.Queue')),
            ],
        ),
        migrations.AddField(
            model_name='queue',
            name='resource_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartqueue.Resource'),
        ),
    ]
